apiVersion: v1
kind: ConfigMap
metadata:
    name: banking-config
data:
    ENVIRONMENT: "production"
    ACCOUNT_SERVICE_URL: "http://account-service:8081"
    TRANSACTION_SERVICE_URL: "http://transaction-service:8083"
    AUTH_SERVICE_URL: "http://auth-service:8082"
